# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:

    docker:
      - image: cimg/base:2022.06

    steps:
    # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.18
          # docker_layer_caching: true
      - checkout
      #Enable Swarm Mode
      - run:
          name: Enable Swarm mode in Docker
          command: docker swarm init

      # Start service
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run my-image
            docker exec my-image curl --retry 10 --retry-connrefused http://localhost:5432

      #Install Maven and Ant
      - run:
          name: install Maven and Ant
          command: sudo apt-get update && sudo apt-get install -y ant maven
     
     #Install Maven and Ant
      - run:
          name: Build Sync-Endpoint
          command: mvn clean install
  # machine-work:
  #   machine:
  #     image: ubuntu-2204:2022.04.2
  #   steps:
  #       - checkout
  #       - run:
  #           name: Enable Swarm Mode
  #           command: docker swarm init
  #       - run:
  #           name: Installe Dependencies (Maven and Ant)
  #           command: sudo apt-get update && sudo apt-get install -y ant maven
  #       - run:
  #           name: build project
  #           command: mvn clean install
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
     # - machine-work
